export const productItems = [
    
        {"id": 1, "name": "Product A", "price": 20, "quantity": 50 , " " : 1},
        {"id": 2, "name": "Product B", "price": 25, "quantity": 40},
        {"id": 3, "name": "Product C", "price": 30, "quantity": 30},
        {"id": 4, "name": "Product D", "price": 15, "quantity": 60},
        {"id": 5, "name": "Product E", "price": 18, "quantity": 55},
        {"id": 6, "name": "Product F", "price": 22, "quantity": 48},
        {"id": 7, "name": "Product G", "price": 28, "quantity": 35},
        {"id": 8, "name": "Product H", "price": 19, "quantity": 52},
        {"id": 9, "name": "Product I", "price": 24, "quantity": 42},
        {"id": 10, "name": "Product J", "price": 17, "quantity": 58},
        {"id": 11, "name": "Product K", "price": 21, "quantity": 45},
        {"id": 12, "name": "Product L", "price": 26, "quantity": 38},
        {"id": 13, "name": "Product M", "price": 32, "quantity": 28},
        {"id": 14, "name": "Product N", "price": 16, "quantity": 62},
        {"id": 15, "name": "Product O", "price": 23, "quantity": 47},
        {"id": 16, "name": "Product P", "price": 27, "quantity": 36},
        {"id": 17, "name": "Product Q", "price": 29, "quantity": 33},
        {"id": 18, "name": "Product R", "price": 14, "quantity": 64},
        {"id": 19, "name": "Product S", "price": 31, "quantity": 29},
        {"id": 20, "name": "Product T", "price": 18, "quantity": 53},
        {"id": 21, "name": "Product U", "price": 22, "quantity": 50},
        {"id": 22, "name": "Product V", "price": 26, "quantity": 46},
        {"id": 23, "name": "Product W", "price": 19, "quantity": 41},
        {"id": 24, "name": "Product X", "price": 15, "quantity": 57},
        {"id": 25, "name": "Product Y", "price": 31, "quantity": 34},
        {"id": 26, "name": "Product Z", "price": 20, "quantity": 49},
        {"id": 27, "name": "Product AA", "price": 23, "quantity": 44},
        {"id": 28, "name": "Product BB", "price": 29, "quantity": 39},
        {"id": 29, "name": "Product CC", "price": 16, "quantity": 55},
        {"id": 30, "name": "Product DD", "price": 18, "quantity": 51},
        {"id": 31, "name": "Product EE", "price": 24, "quantity": 37},
        {"id": 32, "name": "Product FF", "price": 27, "quantity": 32},
        {"id": 33, "name": "Product GG", "price": 21, "quantity": 48},
        {"id": 34, "name": "Product HH", "price": 25, "quantity": 43},
        {"id": 35, "name": "Product II", "price": 30, "quantity": 29},
        {"id": 36, "name": "Product JJ", "price": 17, "quantity": 56},
        {"id": 37, "name": "Product KK", "price": 19, "quantity": 52},
        {"id": 38, "name": "Product LL", "price": 22, "quantity": 47},
        {"id": 39, "name": "Product MM", "price": 28, "quantity": 42},
        {"id": 40, "name": "Product NN", "price": 14, "quantity": 58},
        {"id": 41, "name": "Product OO", "price": 20, "quantity": 45},
        {"id": 42, "name": "Product PP", "price": 23, "quantity": 41},
        {"id": 43, "name": "Product QQ", "price": 29, "quantity": 36},
        {"id": 44, "name": "Product RR", "price": 16, "quantity": 63},
        {"id": 45, "name": "Product SS", "price": 31, "quantity": 30},
        {"id": 46, "name": "Product TT", "price": 18, "quantity": 54},
        {"id": 47, "name": "Product UU", "price": 24, "quantity": 40},
        {"id": 48, "name": "Product VV", "price": 27, "quantity": 35},
        {"id": 49, "name": "Product WW", "price": 21, "quantity": 50},
        {"id": 50, "name": "Product XX", "price": 25, "quantity": 45},
        {"id": 51, "name": "Product YY", "price": 30, "quantity": 31},
        {"id": 52, "name": "Product ZZ", "price": 15, "quantity": 57},
        {"id": 53, "name": "Product AAA", "price": 19, "quantity": 53},
        {"id": 54, "name": "Product BBB", "price": 22, "quantity": 48},
        {"id": 55, "name": "Product CCC", "price": 28, "quantity": 34},
        {"id": 56, "name": "Product DDD", "price": 16, "quantity": 59},
        {"id": 57, "name": "Product EEE", "price": 23, "quantity": 44},
      
];

export const customerItems = [
        {"id": 1, "First-Name": "Alice", "Last-Name": "Johnson", "Email": "alice@example.com", "Mobile": "555-123-4567", "Rewards": 42, "Membership": "✔️"},
        {"id": 2, "First-Name": "Bob", "Last-Name": "Smith", "Email": "bob@example.com", "Mobile": "555-234-5678", "Rewards": 18, "Membership": "❌"},
        {"id": 3, "First-Name": "Charlie", "Last-Name": "Brown", "Email": "charlie@example.com", "Mobile": "555-345-6789", "Rewards": 27, "Membership": "✔️"},
        {"id": 4, "First-Name": "David", "Last-Name": "Williams", "Email": "david@example.com", "Mobile": "555-456-7890", "Rewards": 33, "Membership": "❌"},
        {"id": 5, "First-Name": "Eva", "Last-Name": "Davis", "Email": "eva@example.com", "Mobile": "555-567-8901", "Rewards": 15, "Membership": "✔️"},
        {"id": 6, "First-Name": "Frank", "Last-Name": "Miller", "Email": "frank@example.com", "Mobile": "555-678-9012", "Rewards": 50, "Membership": "❌"},
        {"id": 7, "First-Name": "Grace", "Last-Name": "Johnson", "Email": "grace@example.com", "Mobile": "555-789-0123", "Rewards": 23, "Membership": "✔️"},
        {"id": 8, "First-Name": "Harry", "Last-Name": "Thomas", "Email": "harry@example.com", "Mobile": "555-890-1234", "Rewards": 10, "Membership": "❌"},
        {"id": 9, "First-Name": "Ivy", "Last-Name": "White", "Email": "ivy@example.com", "Mobile": "555-901-2345", "Rewards": 37, "Membership": "✔️"},
        {"id": 10, "First-Name": "Jack", "Last-Name": "Taylor", "Email": "jack@example.com", "Mobile": "555-012-3456", "Rewards": 29, "Membership": "❌"},
        {"id": 11, "First-Name": "Karen", "Last-Name": "Brown", "Email": "karen@example.com", "Mobile": "555-123-4567", "Rewards": 14, "Membership": "✔️"},
        {"id": 12, "First-Name": "Leo", "Last-Name": "Davis", "Email": "leo@example.com", "Mobile": "555-234-5678", "Rewards": 45, "Membership": "❌"},
        {"id": 13, "First-Name": "Mia", "Last-Name": "Smith", "Email": "mia@example.com", "Mobile": "555-345-6789", "Rewards": 22, "Membership": "✔️"},
        {"id": 14, "First-Name": "Nathan", "Last-Name": "White", "Email": "nathan@example.com", "Mobile": "555-456-7890", "Rewards": 31, "Membership": "❌"},
        {"id": 15, "First-Name": "Olivia", "Last-Name": "Miller", "Email": "olivia@example.com", "Mobile": "555-567-8901", "Rewards": 19, "Membership": "✔️"},
        {"id": 16, "First-Name": "Paul", "Last-Name": "Johnson", "Email": "paul@example.com", "Mobile": "555-678-9012", "Rewards": 28, "Membership": "❌"},
        {"id": 17, "First-Name": "Quinn", "Last-Name": "Taylor", "Email": "quinn@example.com", "Mobile": "555-789-0123", "Rewards": 36, "Membership": "✔️"},
        {"id": 18, "First-Name": "Ryan", "Last-Name": "Thomas", "Email": "ryan@example.com", "Mobile": "555-890-1234", "Rewards": 13, "Membership": "❌"},
        {"id": 19, "First-Name": "Sophia", "Last-Name": "Williams", "Email": "sophia@example.com", "Mobile": "555-901-2345", "Rewards": 26, "Membership": "✔️"},
        {"id": 20, "First-Name": "Tom", "Last-Name": "Miller", "Email": "tom@example.com", "Mobile": "555-012-3456", "Rewards": 41, "Membership": "❌"}
      ];

      export const orderItems = [       

        
                {"Refrence": "order-1-1-1-1", "Order-items": 3, "Amount": 120, "Customer": "Johnson Smith", "Order-date": "2017-02-03", "Shipping-date": "2017-02-10"},
                {"Refrence": "order-2-2-2-2", "Order-items": 1, "Amount": 75, "Customer": "Emily Davis", "Order-date": "2017-05-15", "Shipping-date": "2017-05-20"},
                {"Refrence": "order-3-3-3-3", "Order-items": 4, "Amount": 200, "Customer": "Michael Taylor", "Order-date": "2017-08-22", "Shipping-date": "2017-09-01"},
                {"Refrence": "order-4-4-4-4", "Order-items": 2, "Amount": 150, "Customer": "Sophia Brown", "Order-date": "2017-11-10", "Shipping-date": "2017-11-18"},
                {"Refrence": "order-5-5-5-5", "Order-items": 1, "Amount": 50, "Customer": "Charlie Johnson", "Order-date": "2018-03-05", "Shipping-date": "2018-03-12"},
                {"Refrence": "order-6-6-6-6", "Order-items": 3, "Amount": 180, "Customer": "Eva Miller", "Order-date": "2018-06-17", "Shipping-date": "2018-06-25"},
                {"Refrence": "order-7-7-7-7", "Order-items": 2, "Amount": 95, "Customer": "Nathan Thomas", "Order-date": "2018-09-30", "Shipping-date": "2018-10-07"},
                {"Refrence": "order-8-8-8-8", "Order-items": 4, "Amount": 220, "Customer": "Olivia White", "Order-date": "2019-01-12", "Shipping-date": "2019-01-20"},
                {"Refrence": "order-9-9-9-9", "Order-items": 1, "Amount": 60, "Customer": "Jackie Miller", "Order-date": "2019-04-25", "Shipping-date": "2019-05-01"},
                {"Refrence": "order-10-10-10-10", "Order-items": 3, "Amount": 170, "Customer": "Ryan Taylor", "Order-date": "2019-08-08", "Shipping-date": "2019-08-15"}
              
              
        

];